name: Sync Repos

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 * * * *"

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          repository: Cyfarw9dd/TallNeck-private
          token: ${{ secrets.TOKEN }}

      - name: Sync to destination repo
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "Cyfarw9dd/TallNeck-private"
          source_branch: "master"
          destination_branch: "master"    # 使用 destination_branch 而不是 target_branch
          github_token: ${{ secrets.TOKEN }}